### PR TITLE
Staging -> Production

### PR DESCRIPTION
**Pull request by nleck**
Release to Production

### CODE REVIEW

**Review by jwalterlarson — APPROVED** [review]
Approve.

**Comment by nleck** [comment]
@jwalterlarson I'll close this. We don't want two sets of jobs running in production. Need to test in staging first

**Review by mufaddaltaiyeb — APPROVED** [review]
Updates fit for purpose.

**Comment by nleck** [comment]
@mufaddaltaiyeb @jwalterlarson  we need to schedule this PR as it would mean two sets of batch programs running in production. I'll hold this in "draft" mode until we have done more tests in Develop/Staging.

**Pull request merged**
